name: 'Contentful Migration'
description: 'Run a Migration against your Contentful space'
inputs:
  space_id:
    description: "The id of the contentful space"
    required: true
  management_api_key:
    description: "The management-api key for contentful"
    required: true
  version_content_type:
    description: "The content-type that tracks the version"
    required: false
    default: "versionTracking"
  version_field:
    description: "The field that carries the version number"
    required: false
    default: "version"
  master_pattern:
    description: "The pattern that should be used for the new master"
    required: false
    default: "master-[YYYY]-[MM]-[DD]-[mm][ss]"
  feature_pattern:
    description: "The pattern that should be used for the new feature"
    required: false
    default: "GH-[branch]"
  delete_feature:
    description: "The head branch will be deleted after it was merged"
    required: false
    default: "false"
  set_alias:
    description: "The master will be aliased to the new master"
    required: false
    default: "false"
  migrations_dir:
    description: "The directory to look for migrations"
    required: false
    default: "migrations"

outputs:
  environment_url:
    description: "Contentful environment URL"
  environment_name:
    description: "Contentful environment name"

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "upload-cloud"
  color: "blue"
